---
title: 'CURSO DE EXTENSÃO - "R PARA SAÚDE": INFORMÁTICA APLICADA À PESQUISA CIENTÍFICA'
author: Ryan Pablo Alves de Almeida Pires, Maria do Carmo Soares de Lima e Carla Vitória Alves Cavalcante
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
    html_document:
       highlight: textmate
       includes:
         in_header: "C:/Users/ryall/Desktop/R/r_p_saude/r_p_saude/modulos/img/header.html"
       theme: flatly
       number_sections: yes
       toc: yes
       toc_float:
         collapsed: yes
         smooth_scroll: no
---


# Sobre o curso e os autores

Apostilas dos códigos utilizados nas aulas "Curso: R para Saúde" realizado em parceria entre o Departamento de Ciência Política e o Programa de Pós-graduação em Nutrição da Universidade Federal de Pernambuco. Curso ministrado pelos docentes: [Prof.ª Dr.ª Maria do Carmo](http://lattes.cnpq.br/6914758127566065) e o [Prof. Dalson Britto](http://lattes.cnpq.br/6683806605359913) e monitorado por [Ryan Almeida](https://github.com/ryallmeida) e [Carla Cavalcante](https://github.com/Carla-Cavalcante)

## Maria Soares

## Ryan Almeida

## Carla Cavalcante 

## Dalson Britto

# Fundamentos em R

## Preparação ambiental

## Programação orientada à objetos

## Operadores Matemáticos

## Operadores Lógicos

# Referências e materiais de apoio

[ANJOS, Adilson dos. Estatística básica com uso do software R. Curitiba: Departamento de Estatística – UFPR, 2010.](https://docs.ufpr.br/~aanjos/TRI/R/rbasico.pdf)

[BOLFARINE, Heleno; SANDOVAL, Mônica Carneiro. Introdução à inferência estatística. São Paulo: Blucher, 2018.](https://docs.ufpr.br/~lucambio/CE210/LIVRO%20de%20infer%EAncia%20bolfarine.pdf)

[CHAOUBAH, A. A importância da Bioestatística na formação de um profissional de Saúde. Revista Brasileira de Oftalmologia](https://www.scielo.br/j/rbof/a/ZnvJ63VgxhbhWthX9nVBWgg/?format=html&lang=pt)

[CASELLA, George; BERGER, Roger L. Statistical inference. 2nd ed. Belmont, CA: Duxbury Press, 2002.](https://www.amazon.com.br/Statistical-Inference-George-Casella/dp/1032593032/ref=sr_1_1?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=32UCM6L87P7E1&dib=eyJ2IjoiMSJ9.Ax3SRemiZDkg6JQcCEjJyvkHFeo9-o-Z8AwK3hLco-p9p1QN5dOVAGYp-1RLcf0wX5z0QLCKtHCJXsXauosVYrzAX5WOG4kYqeJPoTC-M9U8evy8ED_8XzKushqfNV4-0qSUPZJoSDMvHHf9QgkfYZfShcnEblFie46_09JPowIsR77rDAaw3oHsj0MwLZxl.G8t2XqvTavTKwvfQPgVAJ4QK2bSzEZiEhoypCq-SWDI&dib_tag=se&keywords=Statistical+Inference+ByGeorge+Casella%2C+Roger+Berger&qid=1761863452&sprefix=statistical+inference+bygeorge+casella+roger+berger%2Caps%2C229&sr=8-1&ufe=app_do%3Aamzn1.fos.4bddec23-2dcf-4403-8597-e1a02442043d)

[Curso: Ciência de Dados em R](https://livro.curso-r.com/index.html)

[Figueiredo Filho, Dalson, et al. "O que fazer e o que não fazer com a regressão: pressupostos e aplicações do modelo linear de Mínimos Quadrados Ordinários (MQO)." Revista Política Hoje 20.1 (2011): 44-99.](https://www.academia.edu/8169376/O_que_Fazer_e_o_que_N%C3%A3o_Fazer_com_a_Regress%C3%A3o_pressupostos_e_aplica%C3%A7%C3%B5es_do_modelo_linear_de_M%C3%ADnimos_Quadrados_Ordin%C3%A1rios_MQO)

[Grolemund, Garrett. Hands-on programming with R. " O'Reilly Media, Inc.", 2014.](https://rstudio-education.github.io/hopr/basics.html)

[Hadley Wickham (2010): Uma gramática em camadas de gráficos, Journal of Computational and Graphical Statistics](https://byrneslab.net/classes/biol607/readings/wickham_layered-grammar.pdf)

[JAMES, Gareth et al. An Introduction to Statistical Learning: with Applications in R. Second Edition. (S.l.): (s.n.), 2023.](https://www.statlearning.com/)

[Kuhn, Max, and Julia Silge. Tidy modeling with R: A framework for modeling in the tidyverse. " O'Reilly Media, Inc.", 2022.](https://www.tmwr.org/)

[LANDEIRO, Victor Lemes. Introdução ao uso do programa R. Manaus: Instituto Nacional de Pesquisas da Amazônia, Programa de Pós-Graduação em Ecologia](https://cran.r-project.org/doc/contrib/Landeiro-Introducao.pdf)

MARTIN, Peter. Linear Regression: an introduction to statistical models. London: SAGE Publications, 2021. 978-1-5264-2417-4. (The SAGE Quantitative Research Kit).

[The R Graph Gallery (Site para ver modelos de possíveis gráficos no R)](https://r-graph-gallery.com/index.html)

[Wickham H (2014). Dados organizados. Journal of Statistical Software. Volume 59, Edição 10.](https://vita.had.co.nz/papers/tidy-data.pdf)

[Wickham, Hadley, Mine Çetinkaya-Rundel, and Garrett Grolemund. R für Data Science: Daten importieren, bereinigen, umformen und visualisieren. O'Reilly, 2024.](https://pt.r4ds.hadley.nz/)

Mais informações podem ser encontradas em [tidyverse.org](https://tidyverse.org/)

Mais informações sobre **Regressão Linear** na área de **Nutrição e Saúde** podem sem encontradas abaixo

[Costa et tal. Evolução do excesso de peso e fatores associados em mulheres de 10 a 49 anos em Pernambuco, Nordeste, Brasil. Revista de Nutrição](https://www.scielo.br/j/rn/a/4SnTxv5qmCP4kjgPRNBN3QC/?lang=pt)

[Pinho et tal. Excesso de peso em adultos do Estado de Pernambuco, Brasil: magnitude e fatores associados. Cadernos de Saúde Pública´](https://www.scielo.br/j/csp/a/yVJSvdS5Xptjh3dHZL4c7GS/?lang=pt)

[Silva et tal. Situação de insegurança alimentar em domicílios de Pernambuco, Região Nordeste do Brasil: contribuições para discussão da violação do direito à alimentação. Saúde e Sociedade](https://www.scielo.br/j/sausoc/a/MJNKgg3CTPMLt8DMm3RwjQH/abstract/?lang=pt)

